import Navbar from "@/pages/navbar/Navbar";
import "./globals.css";
import Footer from "@/pages/footer/page";
import Providers from "@/redux/providers";
import ProviderTheme from "@/providerTheme/ProviderTheme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ProviderTheme>
            <div className="container">
              <div className="w-[80%] mx-auto space-y-10">
                {/* Navbar */}
                <Navbar />

                {/* Children Pages */}
                <div className="min-h-screen">{children}</div>

                {/* Footer */}
                <Footer />
              </div>
            </div>
          </ProviderTheme>
        </Providers>
      </body>
    </html>
  );
}
